
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module sample(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout			    [35:0]		GPIO
	
);



//=======================================================
// declarations
//=======================================================

wire clk_200;
wire locked;
reg toggle;

pll_200MHz pll_200MHz_inst(
	MAX10_CLK1_50,
	clk_200,
	locked);
	
reg [4:0] count;
reg reset;

timer_5ns timer_5ns_inst(
	clk_200,
	reset,
	count
);

//=======================================================
//  Structural coding
//=======================================================

always @(posedge clk_200) begin
    if (count == 4'b01111)
        toggle <= ~toggle;
end

assign GPIO[0] = toggle ? 1'bz : 1'b0;

endmodule
